name : Run Dagger pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:
  

jobs:
    dagger:
          name: Run Dagger pipeline
          runs-on: ubuntu-latest

          steps:
              - name: Checkout code
                uses: action/checkout@v7.0.1

              - name: Setup up Go
                uses: actions/setup-go@7.0.0
                with:
                  go-version: 1.27.1
                  cache: false

              - name: Run Dagger pipeline
                uses: dagger/dagger-for-github@v8.4.1
                with:
                  workdir: go 
                  verb: run 
                  args: go run pipeline.go
                  version: "0.21.10"